<?php

/**
 * @file
 * Campo de busca para Descritores em Ciências da Saúde (DeCS).
 *
 */

/***************************************************************
 * Field Type API hooks
 ***************************************************************/

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function decs_field_info() {

	return array(
		'decs_decs' => array(
		'label' => t('Descritores em Ciências da Saúde'),
		'description' => t('Campo de busca para Descritores em Ciências da Saúde (DeCS).'),
		'default_widget' => 'decs_field',
		'default_formatter' => 'decs_field',
		),
	);
}

/**
 * Implements hook_field_is_empty().
 */
function decs_field_is_empty($item, $field) {

	return false;
}

/**
 * Implements hook_field_widget_info().
 */
function decs_field_widget_info() {

	return array(
		'decs_field' => array(
			'label' => t('Campo DeCS'), 
			'field types' => array('decs_decs'), 
			),
		);
}

/**
 * Implements hook_field_widget_form().
 */
function decs_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
	
	$element += array(
		'#type' => 'textfield',
		'#default_value' => '',
	);

	return $element;	
}

/***********************************************************************
 *  Field Type API: Formatter
 *
 *  These are the api hooks that present formatted (themed) output to the
 *  user.
 **********************************************************************/

/**
 * Implements hook_field_formatter_info().
 */
/*
function decs_field_formatter_info() {
	
	return array(
		'decs_field' => array(
		'label' => t('Campo DeCS'),
		'field types' => array('decs_decs'),
		),
	);
}
*/

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function decs_help($path, $arg) {

	switch ($path) {
		case "admin/help#decs":
		return '<p>'. t("Fornece mecanismo para usar os Descritores em Ciências da Saúde (DeCS)") .'</p>';
		break;
	}
}